services:
  client:
    restart: always
    ports:
      - 80:80

  server:
    build: ./Dockerfile
    restart: always
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - API_KEY=f0f8250a24f84c1bb693095488b4830a
    ports:
      - 3000:3000

  ai:
    restart: always
    environment:
      - HOST=0.0.0.0
      - PORT=5000
    ports:
      - 5000:5000

  database:
    image: redis
    restart: always